{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import requests\n",
    "import json\n",
    "import pandas as pd\n",
    "import os\n",
    "from dotenv import load_dotenv\n",
    "load_dotenv()\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Aqui uso la api de Deezer primero saco el token que nos lo dan con el numero de usuario"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WE HAVE APIKEY\n"
     ]
    }
   ],
   "source": [
    "apikey = os.getenv(\"apikey\")\n",
    "print(\"WE HAVE APIKEY\") if apikey else print(\"NO APIKEY FOUND\")\n",
    "\n",
    "urlautentificador = f\"https://api.deezer.com/user/{apikey}\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Response [200]>"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "res = requests.get(urlautentificador)\n",
    "res\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Probamos uno para sacar la formula para sacar el album\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "artists_url = \"https://api.deezer.com/search?q=artist:'Arizona Zervas'\"\n",
    "artists_response = requests.get(artists_url)\n",
    "album =artists_response.json()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('clean.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['Unnamed: 0', 'title', 'artist', 'top genre', 'year', 'country', 'val'], dtype='object')"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.columns"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "Selecionamos solo las columnas que vamos a usar"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>artist</th>\n",
       "      <th>top genre</th>\n",
       "      <th>year</th>\n",
       "      <th>country</th>\n",
       "      <th>val</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>10,000 Hours (with Justin Bieber)</td>\n",
       "      <td>Dan + Shay</td>\n",
       "      <td>contemporary country</td>\n",
       "      <td>2019</td>\n",
       "      <td>indonesia</td>\n",
       "      <td>43</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>10,000 Hours (with Justin Bieber)</td>\n",
       "      <td>Dan + Shay</td>\n",
       "      <td>contemporary country</td>\n",
       "      <td>2019</td>\n",
       "      <td>malasya</td>\n",
       "      <td>43</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>100 Degrees</td>\n",
       "      <td>Rich Brian</td>\n",
       "      <td>indonesian hip hop</td>\n",
       "      <td>2019</td>\n",
       "      <td>indonesia</td>\n",
       "      <td>66</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>105 F Remix</td>\n",
       "      <td>KEVVO</td>\n",
       "      <td>perreo</td>\n",
       "      <td>2019</td>\n",
       "      <td>chile</td>\n",
       "      <td>74</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>105 F Remix</td>\n",
       "      <td>KEVVO</td>\n",
       "      <td>perreo</td>\n",
       "      <td>2019</td>\n",
       "      <td>spain</td>\n",
       "      <td>74</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>930</th>\n",
       "      <td>menina solta</td>\n",
       "      <td>Giulia Be</td>\n",
       "      <td>pop nacional</td>\n",
       "      <td>2019</td>\n",
       "      <td>brazil</td>\n",
       "      <td>67</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>931</th>\n",
       "      <td>occh1 purpl3 - feat. Marracash</td>\n",
       "      <td>tha Supreme</td>\n",
       "      <td>trap italiana</td>\n",
       "      <td>2019</td>\n",
       "      <td>italy</td>\n",
       "      <td>55</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>932</th>\n",
       "      <td>quando a bad bater - ao vivo</td>\n",
       "      <td>Luan Santana</td>\n",
       "      <td>funk carioca</td>\n",
       "      <td>2019</td>\n",
       "      <td>brazil</td>\n",
       "      <td>53</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>933</th>\n",
       "      <td>sw1n6o - feat. Salmo</td>\n",
       "      <td>tha Supreme</td>\n",
       "      <td>trap italiana</td>\n",
       "      <td>2019</td>\n",
       "      <td>italy</td>\n",
       "      <td>79</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>934</th>\n",
       "      <td>Áudio - Ao Vivo em Brasília</td>\n",
       "      <td>Diego &amp; Victor Hugo</td>\n",
       "      <td>sertanejo pop</td>\n",
       "      <td>2019</td>\n",
       "      <td>brazil</td>\n",
       "      <td>45</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>935 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                 title               artist  \\\n",
       "0    10,000 Hours (with Justin Bieber)           Dan + Shay   \n",
       "1    10,000 Hours (with Justin Bieber)           Dan + Shay   \n",
       "2                          100 Degrees           Rich Brian   \n",
       "3                          105 F Remix                KEVVO   \n",
       "4                          105 F Remix                KEVVO   \n",
       "..                                 ...                  ...   \n",
       "930                       menina solta            Giulia Be   \n",
       "931     occh1 purpl3 - feat. Marracash          tha Supreme   \n",
       "932       quando a bad bater - ao vivo         Luan Santana   \n",
       "933               sw1n6o - feat. Salmo          tha Supreme   \n",
       "934        Áudio - Ao Vivo em Brasília  Diego & Victor Hugo   \n",
       "\n",
       "                top genre  year    country  val  \n",
       "0    contemporary country  2019  indonesia   43  \n",
       "1    contemporary country  2019    malasya   43  \n",
       "2      indonesian hip hop  2019  indonesia   66  \n",
       "3                  perreo  2019      chile   74  \n",
       "4                  perreo  2019      spain   74  \n",
       "..                    ...   ...        ...  ...  \n",
       "930          pop nacional  2019     brazil   67  \n",
       "931         trap italiana  2019      italy   55  \n",
       "932          funk carioca  2019     brazil   53  \n",
       "933         trap italiana  2019      italy   79  \n",
       "934         sertanejo pop  2019     brazil   45  \n",
       "\n",
       "[935 rows x 6 columns]"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "d =['title', 'artist', 'top genre', 'year', 'country', 'val']\n",
    "df = df[d]\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['10,000 Hours (with Justin Bieber)',\n",
       " '10,000 Hours (with Justin Bieber)',\n",
       " '100 Degrees',\n",
       " '105 F Remix',\n",
       " '105 F Remix',\n",
       " '200 km/h',\n",
       " '2000 Miles - 2007 Remaster',\n",
       " '3 Batidas - Ao Vivo',\n",
       " '7 rings',\n",
       " '8 Days of Christmas',\n",
       " '8 Parche',\n",
       " '93% [Tijuana]',\n",
       " 'A Culpa é do Meu Grau (feat. Zé Neto & Cristiano) - Ao Vivo em Brasília',\n",
       " 'A Dónde Vamos',\n",
       " 'A Gente Fez Amor - Ao Vivo',\n",
       " 'A Holly Jolly Christmas - Single Version',\n",
       " 'A Holly Jolly Christmas - Single Version',\n",
       " 'A Holly Jolly Christmas - Single Version',\n",
       " 'A Holly Jolly Christmas - Single Version',\n",
       " 'A Holly Jolly Christmas - Single Version',\n",
       " 'A Holly Jolly Christmas - Single Version',\n",
       " 'ANSIA NO',\n",
       " 'Adan y Eva',\n",
       " 'Adicto (with Anuel AA & Ozuna)',\n",
       " 'Adicto (with Anuel AA & Ozuna)',\n",
       " 'Adicto (with Anuel AA & Ozuna)',\n",
       " 'Adicto (with Anuel AA & Ozuna)',\n",
       " 'Adicto (with Anuel AA & Ozuna)',\n",
       " 'Adonay',\n",
       " 'Adore You',\n",
       " 'Adore You',\n",
       " 'Adu Rayu',\n",
       " 'Akulaleki',\n",
       " 'Algo Mais (Amante) - Ao Vivo',\n",
       " 'Alguien Me Gusta',\n",
       " 'Algún Día Volveras',\n",
       " 'Alien',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'All I Want for Christmas Is You',\n",
       " 'Alocao (With Bad Gyal)',\n",
       " 'Amor a Primera Vista',\n",
       " 'April',\n",
       " 'Aristocrate',\n",
       " 'Atrévete',\n",
       " 'Avant toi',\n",
       " 'Aventura',\n",
       " 'Aventura',\n",
       " 'Aventura',\n",
       " 'Aventura',\n",
       " 'Aventura',\n",
       " 'Aventurero',\n",
       " 'Ayy Macarena',\n",
       " 'Ayy Macarena',\n",
       " 'Aí Eu Bebo - Ao Vivo',\n",
       " 'B11 (feat. Myke Towers)',\n",
       " 'B11 (feat. Myke Towers)',\n",
       " 'BOP',\n",
       " 'BRAVI A CADERE - I polmoni',\n",
       " \"Baby It's Cold Outside (duet with Michael Bublé)\",\n",
       " \"Baby, It's Cold Outside\",\n",
       " \"Baby, It's Cold Outside\",\n",
       " \"Baby, It's Cold Outside\",\n",
       " 'Baianá',\n",
       " 'Bandit (with YoungBoy Never Broke Again)',\n",
       " 'Barrio',\n",
       " 'Beautiful People (feat. Khalid)',\n",
       " 'Beautiful People (feat. Khalid)',\n",
       " 'Beautiful People (feat. Khalid)',\n",
       " 'Beautiful People (feat. Khalid)',\n",
       " 'Bebi Liguei - Ao Vivo',\n",
       " 'Bebi Minha Bicicleta (Coração Falido) - Ao Vivo',\n",
       " 'Before You Go',\n",
       " 'Bekhayali (From \"Kabir Singh\")',\n",
       " 'Believer',\n",
       " 'Bellaquita',\n",
       " 'Bellaquita - Remix',\n",
       " 'Bellaquita - Remix',\n",
       " 'Bellaquita - Remix',\n",
       " 'Bellaquita - Remix',\n",
       " 'Bellaquita - Remix',\n",
       " 'Bicara (feat. Monita Tahalea)',\n",
       " 'Blanca Navidad',\n",
       " 'Blanco',\n",
       " 'Blanco',\n",
       " 'Blanco',\n",
       " 'Blanco',\n",
       " 'Blinding Lights',\n",
       " 'Blinding Lights',\n",
       " 'Blinding Lights',\n",
       " 'Blinding Lights',\n",
       " 'Blinding Lights',\n",
       " 'Blinding Lights',\n",
       " 'Blinding Lights',\n",
       " 'Block',\n",
       " 'Blue Christmas',\n",
       " 'Blue Christmas',\n",
       " 'Blue Christmas',\n",
       " 'Blue Christmas',\n",
       " 'Blue Christmas',\n",
       " 'Blue Christmas',\n",
       " 'Bossoli',\n",
       " 'Boy With Luv (feat. Halsey)',\n",
       " 'Boy With Luv (feat. Halsey)',\n",
       " 'Bâtiment',\n",
       " 'C90 - Remix',\n",
       " 'CANGURO',\n",
       " 'CHARLES MANSON (BUON NATALE2) (feat. Lazza) - feat. Dani Faiv, Nitro',\n",
       " 'COLT',\n",
       " 'CRUDELIA - I nervi',\n",
       " 'Callaita',\n",
       " 'Callaita',\n",
       " 'Callaita',\n",
       " 'Callaita',\n",
       " 'Callaita',\n",
       " 'Calma - Remix',\n",
       " 'Can We Kiss Forever?',\n",
       " 'Cariñito',\n",
       " 'Carol of the Bells',\n",
       " 'Carreira Solo - Ao Vivo',\n",
       " 'Celengan Rindu',\n",
       " 'Chal Bombay',\n",
       " 'Chama Ela (feat. Pedro Sampaio)',\n",
       " 'Chandigarh Mein',\n",
       " 'Cheirosa - Ao Vivo',\n",
       " 'Chiasso',\n",
       " 'China',\n",
       " 'China',\n",
       " 'China',\n",
       " 'China',\n",
       " 'China',\n",
       " 'Christmas (Baby Please Come Home)',\n",
       " 'Christmas (Baby Please Come Home)',\n",
       " 'Christmas (Baby Please Come Home)',\n",
       " 'Christmas (Baby Please Come Home)',\n",
       " 'Christmas (Baby Please Come Home)',\n",
       " 'Christmas (Baby Please Come Home)',\n",
       " 'Christmas (Baby Please Come Home)',\n",
       " 'Christmas (Baby Please Come Home)',\n",
       " 'Christmas (Baby Please Come Home)',\n",
       " 'Christmas (Baby Please Come Home)',\n",
       " 'Christmas Lights',\n",
       " 'Christmas Lights',\n",
       " 'Christmas Lights',\n",
       " 'Christmas Lights',\n",
       " 'Christmas Lights',\n",
       " 'Christmas Time',\n",
       " 'Christmas Time Is Here - Vocal',\n",
       " 'Cin Cin',\n",
       " 'Cinta Luar Biasa',\n",
       " 'Cinta Luar Biasa',\n",
       " 'Circles',\n",
       " 'Circles',\n",
       " 'Circles',\n",
       " 'Circles',\n",
       " 'Circles',\n",
       " 'Circles',\n",
       " 'Circles',\n",
       " 'Circles',\n",
       " 'Com ou Sem Mim (Ao Vivo em Fortaleza)',\n",
       " 'Combatchy (feat. MC Rebecca)',\n",
       " 'Compliqué',\n",
       " 'Con Altura',\n",
       " 'Con Altura',\n",
       " 'Con Altura',\n",
       " 'Con Altura',\n",
       " 'Con Calma',\n",
       " 'Contando Lunares (feat. Cruz Cafuné)',\n",
       " 'Contatinho - Ao Vivo Em São Paulo / 2019',\n",
       " 'Coronao Now',\n",
       " 'Cuerpo en Venta',\n",
       " 'Cómo estás',\n",
       " 'Côte Ouest',\n",
       " 'DJ No Pare (feat. Zion, Dalex, Lenny Tavárez) - Remix',\n",
       " 'DJ No Pare (feat. Zion, Dalex, Lenny Tavárez) - Remix',\n",
       " 'DJ No Pare (feat. Zion, Dalex, Lenny Tavárez) - Remix',\n",
       " 'DJ No Pare (feat. Zion, Dalex, Lenny Tavárez) - Remix',\n",
       " 'Dan...',\n",
       " 'Dance Like',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Dance Monkey',\n",
       " 'Daniela',\n",
       " \"Dans l'univers\",\n",
       " 'Der Bratan bleibt der gleiche',\n",
       " 'Desconocidos',\n",
       " 'Detente',\n",
       " 'Dheeme Dheeme (From \"Pati Patni Aur Woh\")',\n",
       " 'Distant',\n",
       " \"Do They Know It's Christmas? - 1984 Version\",\n",
       " \"Do They Know It's Christmas? - 1984 Version\",\n",
       " \"Do They Know It's Christmas? - 1984 Version\",\n",
       " \"Do They Know It's Christmas? - 1984 Version\",\n",
       " \"Do They Know It's Christmas? - 1984 Version\",\n",
       " \"Do They Know It's Christmas? - 1984 Version\",\n",
       " \"Do They Know It's Christmas? - 1984 Version\",\n",
       " 'Do You Hear What I Hear? - Remastered 2006',\n",
       " 'Do You Hear What I Hear? - Remastered 2006',\n",
       " 'Doch in der Nacht',\n",
       " 'Dois Lados',\n",
       " 'Don\\'t Be Shy Again (From \"Bala\")',\n",
       " \"Don't Start Now\",\n",
       " \"Don't Start Now\",\n",
       " \"Don't Start Now\",\n",
       " \"Don't Start Now\",\n",
       " \"Don't Start Now\",\n",
       " \"Don't Start Now\",\n",
       " 'Driving Home for Christmas - 2019 Remaster',\n",
       " 'Driving Home for Christmas - 2019 Remaster',\n",
       " 'Driving Home for Christmas - 2019 Remaster',\n",
       " 'Driving Home for Christmas - 2019 Remaster',\n",
       " 'Driving Home for Christmas - 2019 Remaster',\n",
       " 'Dulce Pecado',\n",
       " 'Duniyaa (From \"Luka Chuppi\")',\n",
       " 'Easy - Remix',\n",
       " 'Ek Toh Kum Zindagani (From \"Marjaavaan\")',\n",
       " 'El Bombón',\n",
       " 'El Favor (with Nicky Jam & Sech, feat. Farruko, Zion & Lunay)',\n",
       " 'El Favor (with Nicky Jam & Sech, feat. Farruko, Zion & Lunay)',\n",
       " 'El Hijo Ausente',\n",
       " 'El Jornalero (El Hijo de Tuta)',\n",
       " 'Ela Vem',\n",
       " 'Elle est bonne sa mère',\n",
       " 'En Barranquilla Me Quedo',\n",
       " 'Espaçosa Demais - Ao Vivo',\n",
       " 'Fairytale of New York (feat. Kirsty MacColl)',\n",
       " 'Fairytale of New York (feat. Kirsty MacColl)',\n",
       " 'Fairytale of New York (feat. Kirsty MacColl)',\n",
       " 'Fairytale of New York (feat. Kirsty MacColl)',\n",
       " 'Fake News - Ao Vivo',\n",
       " 'Falling',\n",
       " 'Falling',\n",
       " 'Falling',\n",
       " 'Falling',\n",
       " 'Falling',\n",
       " 'Falling',\n",
       " 'Falling',\n",
       " 'Falling',\n",
       " 'Falling',\n",
       " 'Falling',\n",
       " 'Fantasias',\n",
       " 'Fantasias',\n",
       " 'Fantasias',\n",
       " 'Fantasias',\n",
       " 'Fantasias',\n",
       " 'Fantasía',\n",
       " 'Fantasía',\n",
       " 'Feelings',\n",
       " 'Feliz Navidad',\n",
       " 'Feliz Navidad',\n",
       " 'Feliz Navidad',\n",
       " 'Feliz Navidad',\n",
       " 'Feliz Navidad',\n",
       " 'Feliz Navidad',\n",
       " 'Feliz Navidad',\n",
       " 'Feliz Navidad',\n",
       " 'Feliz Navidad',\n",
       " 'Feliz Navidad',\n",
       " 'Ferida Curada',\n",
       " 'Filhall',\n",
       " 'Fingindo Maturidade - Ao Vivo',\n",
       " 'Fire',\n",
       " 'Fresa',\n",
       " 'Fuera De Mi Mente',\n",
       " 'Futsal Shuffle 2020',\n",
       " 'GANG (feat. Geolier)',\n",
       " 'Gaiola É o Troco',\n",
       " 'Gasolina (feat. Gambi)',\n",
       " 'Ghungroo (From \"War\")',\n",
       " 'Gigolò (feat. Sfera Ebbasta & Capo Plaza)',\n",
       " 'God Bless (feat. Damso)',\n",
       " 'Golpe Con Golpe',\n",
       " 'Goodbyes (feat. Young Thug)',\n",
       " 'Goteo',\n",
       " 'Goteo',\n",
       " 'Gurenge',\n",
       " 'HANABI',\n",
       " 'HIGHEST IN THE ROOM',\n",
       " 'Haa Tepok',\n",
       " 'Hakujitsu',\n",
       " 'Hallelujah',\n",
       " 'Halu',\n",
       " 'Hanya Rindu',\n",
       " 'Hanya Rindu',\n",
       " 'Happy Xmas (War Is Over)',\n",
       " 'Happy Xmas (War Is Over) - Remastered',\n",
       " 'Happy Xmas (War Is Over) - Remastered',\n",
       " 'Happy Xmas (War Is Over) - Remastered',\n",
       " 'Happy Xmas (War Is Over) - Remastered',\n",
       " 'Happy Xmas (War Is Over) - Remastered',\n",
       " 'Happy Xmas (War Is Over) - Remastered',\n",
       " 'Happy Xmas (War Is Over) - Remastered',\n",
       " 'Happy Xmas (War Is Over) - Remastered',\n",
       " 'Happy Xmas (War Is Over) - Remastered',\n",
       " 'Hasta Que Salga el Sol',\n",
       " 'Hauli Hauli (From \"De De Pyaar De\")',\n",
       " 'Have Yourself A Merry Little Christmas',\n",
       " 'Have Yourself A Merry Little Christmas',\n",
       " 'Have Yourself A Merry Little Christmas',\n",
       " 'Have Yourself A Merry Little Christmas',\n",
       " 'Have Yourself A Merry Little Christmas',\n",
       " 'Have Yourself A Merry Little Christmas',\n",
       " 'Have Yourself A Merry Little Christmas',\n",
       " 'Have Yourself A Merry Little Christmas',\n",
       " 'Have Yourself A Merry Little Christmas',\n",
       " 'Heartless',\n",
       " 'Hikoutei',\n",
       " 'Hit Contagiante',\n",
       " 'Hoe Het Danst',\n",
       " 'Hola - Remix',\n",
       " 'Hola - Remix',\n",
       " 'Hola - Remix',\n",
       " 'Hola - Remix',\n",
       " 'Hola - Remix',\n",
       " 'Holly & Benji (feat. Capo Plaza & Shiva)',\n",
       " 'Holly Jolly Christmas',\n",
       " 'Holly Jolly Christmas',\n",
       " 'Holly Jolly Christmas',\n",
       " 'Holly Jolly Christmas',\n",
       " 'Holly Jolly Christmas',\n",
       " 'Holly Jolly Christmas',\n",
       " 'Holly Jolly Christmas',\n",
       " 'Holly Jolly Christmas',\n",
       " 'Holly Jolly Christmas',\n",
       " 'Holly Jolly Christmas',\n",
       " 'How Do You Sleep?',\n",
       " 'How to Make Gravy',\n",
       " 'Hé oh',\n",
       " \"I Don't Care (with Justin Bieber)\",\n",
       " \"I Don't Care (with Justin Bieber)\",\n",
       " 'I Love You 3000',\n",
       " 'I Love You 3000',\n",
       " \"I Love You but I'm Letting Go\",\n",
       " 'I Saw Mommy Kissing Santa Claus',\n",
       " 'I Saw Mommy Kissing Santa Claus',\n",
       " 'I Saw Mommy Kissing Santa Claus',\n",
       " 'I Saw Mommy Kissing Santa Claus',\n",
       " \"I'll Be Home for Christmas\",\n",
       " \"I'll Be Home for Christmas\",\n",
       " 'I.F.L.Y.',\n",
       " 'Ik Tera',\n",
       " 'Imaginaste - Remix',\n",
       " 'In der Weihnachtsbäckerei',\n",
       " 'Indeciso',\n",
       " 'Indeciso',\n",
       " 'Indeciso',\n",
       " 'Indeciso',\n",
       " 'Infeliz',\n",
       " 'Into the Unknown',\n",
       " 'Invocada (Participação especial de Léo Santana) - Ao vivo',\n",
       " \"It's Beginning to Look a Lot Like Christmas (with Mitchell Ayres & His Orchestra)\",\n",
       " \"It's Beginning to Look a Lot Like Christmas (with Mitchell Ayres & His Orchestra)\",\n",
       " \"It's Beginning to Look a Lot Like Christmas (with Mitchell Ayres & His Orchestra)\",\n",
       " \"It's Beginning to Look a Lot Like Christmas (with Mitchell Ayres & His Orchestra)\",\n",
       " \"It's Beginning to Look a Lot Like Christmas (with Mitchell Ayres & His Orchestra)\",\n",
       " \"It's Beginning to Look a Lot like Christmas\",\n",
       " \"It's Beginning to Look a Lot like Christmas\",\n",
       " \"It's Beginning to Look a Lot like Christmas\",\n",
       " \"It's Beginning to Look a Lot like Christmas\",\n",
       " \"It's Beginning to Look a Lot like Christmas\",\n",
       " \"It's Beginning to Look a Lot like Christmas\",\n",
       " \"It's Beginning to Look a Lot like Christmas\",\n",
       " \"It's Beginning to Look a Lot like Christmas\",\n",
       " \"It's Beginning to Look a Lot like Christmas\",\n",
       " \"It's Beginning to Look a Lot like Christmas\",\n",
       " \"It's Beginning to Look a Lot like Christmas\",\n",
       " \"It's You\",\n",
       " \"It's You\",\n",
       " \"It's the Most Wonderful Time of the Year\",\n",
       " \"It's the Most Wonderful Time of the Year\",\n",
       " \"It's the Most Wonderful Time of the Year\",\n",
       " \"It's the Most Wonderful Time of the Year\",\n",
       " \"It's the Most Wonderful Time of the Year\",\n",
       " \"It's the Most Wonderful Time of the Year\",\n",
       " \"It's the Most Wonderful Time of the Year\",\n",
       " \"It's the Most Wonderful Time of the Year\",\n",
       " \"It's the Most Wonderful Time of the Year\",\n",
       " 'Jai Jai Shivshankar (From \"War\")',\n",
       " 'Jamais',\n",
       " 'Jerusalem',\n",
       " 'Jingle Bell Rock',\n",
       " 'Jingle Bell Rock',\n",
       " 'Jingle Bell Rock',\n",
       " 'Jingle Bell Rock',\n",
       " 'Jingle Bell Rock',\n",
       " 'Jingle Bell Rock',\n",
       " 'Jingle Bell Rock',\n",
       " 'Jingle Bell Rock',\n",
       " 'Jingle Bell Rock',\n",
       " 'Jingle Bell Rock',\n",
       " 'Jingle Bell Rock',\n",
       " \"Jingle Bell Rock - Daryl's Version\",\n",
       " \"Jingle Bell Rock - Daryl's Version\",\n",
       " \"Jingle Bell Rock - Daryl's Version\",\n",
       " \"Jingle Bell Rock - Daryl's Version\",\n",
       " \"Jingle Bell Rock - Daryl's Version\",\n",
       " \"Jingle Bell Rock - Daryl's Version\",\n",
       " 'Jingle Bells (feat. The Puppini Sisters)',\n",
       " 'Jingle Bells (feat. The Puppini Sisters)',\n",
       " 'Joy To The World',\n",
       " 'Joy To The World',\n",
       " 'KARMA',\n",
       " 'KEIN SCHLAF',\n",
       " 'Kaise Hua (From \"Kabir Singh\")',\n",
       " 'Kalank (Title Track)',\n",
       " 'Kartonyono Medot Janji',\n",
       " 'Keine Liebe',\n",
       " 'Kenangan Manis',\n",
       " 'Kumau Dia',\n",
       " 'LA CANCIÓN',\n",
       " 'LA CANCIÓN',\n",
       " 'LA CANCIÓN',\n",
       " 'LA CANCIÓN',\n",
       " 'La Burrita',\n",
       " 'La Cama',\n",
       " 'La Cama',\n",
       " 'La Cola',\n",
       " 'La Difícil',\n",
       " 'La Noche',\n",
       " 'La Rubia - Remix 2',\n",
       " \"La vie qu'on mène\",\n",
       " 'Labantwana Ama Uber',\n",
       " 'Lalala',\n",
       " 'Las Caleñas',\n",
       " 'Las Cuatro Fiestas',\n",
       " 'Last Christmas',\n",
       " 'Last Christmas',\n",
       " 'Last Christmas',\n",
       " 'Last Christmas',\n",
       " 'Last Christmas',\n",
       " 'Last Christmas',\n",
       " 'Last Christmas',\n",
       " 'Last Christmas',\n",
       " 'Last Christmas',\n",
       " 'Last Christmas',\n",
       " 'Last Christmas',\n",
       " 'Last Christmas',\n",
       " 'Last Christmas',\n",
       " 'Lebih Dari Egoku',\n",
       " 'Lençol Dobrado',\n",
       " 'Let It Snow! Let It Snow! Let It Snow!',\n",
       " 'Let It Snow! Let It Snow! Let It Snow!',\n",
       " 'Let It Snow! Let It Snow! Let It Snow!',\n",
       " 'Let It Snow! Let It Snow! Let It Snow!',\n",
       " 'Let It Snow! Let It Snow! Let It Snow!',\n",
       " 'Let It Snow! Let It Snow! Let It Snow!',\n",
       " 'Let It Snow! Let It Snow! Let It Snow! (with The B. Swanson Quartet)',\n",
       " 'Let It Snow! Let It Snow! Let It Snow! (with The B. Swanson Quartet)',\n",
       " 'Let It Snow! Let It Snow! Let It Snow! (with The B. Swanson Quartet)',\n",
       " 'Let It Snow! Let It Snow! Let It Snow! (with The B. Swanson Quartet)',\n",
       " 'Let It Snow! Let It Snow! Let It Snow! (with The B. Swanson Quartet)',\n",
       " 'Let It Snow! Let It Snow! Let It Snow! (with The B. Swanson Quartet)',\n",
       " 'Let It Snow! Let It Snow! Let It Snow! (with The B. Swanson Quartet)',\n",
       " 'Liberdade Provisória',\n",
       " \"Like It's Christmas\",\n",
       " \"Like It's Christmas\",\n",
       " 'Little Saint Nick - 1991 Remix',\n",
       " 'Little Saint Nick - 1991 Remix',\n",
       " 'Loco',\n",
       " 'Loco',\n",
       " 'Loin de moi',\n",
       " 'Loquito por Ti',\n",
       " 'Lorch',\n",
       " 'Los sabanales',\n",
       " 'Lose You To Love Me',\n",
       " 'Lose You To Love Me',\n",
       " 'Love You Tonight (feat. DJ Maphorisa, Sha Sha & Kabza De Small)',\n",
       " 'Lover (Remix) [feat. Shawn Mendes]',\n",
       " 'Lucid Dreams',\n",
       " 'Lucid Dreams',\n",
       " 'Lucid Dreams',\n",
       " 'Ma belle',\n",
       " 'Ma vie',\n",
       " 'Machigaisagashi',\n",
       " 'Makhna',\n",
       " 'Maman ne le sait pas (feat. Niska)',\n",
       " 'Mami',\n",
       " 'Marie',\n",
       " \"Mary's Boy Child / Oh My Lord\",\n",
       " 'Mayday (feat. Ninho)',\n",
       " 'Me Vas a Extrañar - En Vivo',\n",
       " 'Mean It',\n",
       " 'Mean It',\n",
       " 'Mele Kalikimaka (Merry Christmas)',\n",
       " 'Memories',\n",
       " 'Memories',\n",
       " 'Memories',\n",
       " 'Memories',\n",
       " 'Memories',\n",
       " 'Memories',\n",
       " 'Memories',\n",
       " 'Memories',\n",
       " 'Memories',\n",
       " 'Memories',\n",
       " 'Mere Sohneya (From \"Kabir Singh\")',\n",
       " 'Merry Christmas Everyone',\n",
       " 'Merry Christmas Everyone',\n",
       " 'Merry Christmas Everyone',\n",
       " 'Merry Christmas Everyone',\n",
       " 'Merry Christmas Everyone',\n",
       " 'Merry Christmas Everyone',\n",
       " 'Merry Xmas Everybody',\n",
       " 'Mil Anos - Recorded At Mosh Studios, São Paulo',\n",
       " 'Mimpi (feat. Alif)',\n",
       " 'Mistletoe',\n",
       " 'Mistletoe',\n",
       " 'Mistletoe',\n",
       " 'Mistletoe',\n",
       " 'Mistletoe',\n",
       " 'Mistletoe',\n",
       " 'Mistletoe',\n",
       " 'Mistletoe',\n",
       " 'Mistletoe',\n",
       " 'Mistletoe And Holly - Remastered 1999',\n",
       " 'Mistletoe And Holly - Remastered 1999',\n",
       " 'Mit Dir',\n",
       " 'Mortel',\n",
       " 'Moulaga',\n",
       " 'Mummy Nu Pasand (From \"Jai Mummy Di\")',\n",
       " 'Muqabla (From \"Street Dancer 3D\")',\n",
       " 'My Oh My (feat. DaBaby)',\n",
       " 'My Oh My (feat. DaBaby)',\n",
       " 'My Oh My (feat. DaBaby)',\n",
       " 'My Only Wish (This Year)',\n",
       " 'My Only Wish (This Year)',\n",
       " 'My Only Wish (This Year)',\n",
       " 'Méchant',\n",
       " 'Naah Goriye (From \"Bala\")',\n",
       " 'Nana Thula',\n",
       " 'Navidad, Navidad',\n",
       " 'Ne reviens pas',\n",
       " 'Ne reviens pas',\n",
       " 'Never Go Back',\n",
       " 'Never Seen The Rain',\n",
       " 'Nevermind',\n",
       " 'No Dijeron Nada',\n",
       " 'No Idea',\n",
       " 'No Me Conoce - Remix',\n",
       " 'No Me Conoce - Remix',\n",
       " 'No Me Conoce - Remix',\n",
       " 'No Me Conoce - Remix',\n",
       " 'No Me Conoce - Remix',\n",
       " 'No Te Creas Tan Importante - En Vivo',\n",
       " 'No Te Debí Besar',\n",
       " 'Non Avere Paura',\n",
       " 'Nunca Es Suficiente',\n",
       " 'Nur zur Info',\n",
       " 'Nyaman',\n",
       " 'O Saki Saki (From \"Batla House\")',\n",
       " 'O Tannenbaum',\n",
       " 'Ocho Cuarenta',\n",
       " 'Ojitos Hechiceros',\n",
       " 'Olvídala',\n",
       " 'On My Way',\n",
       " 'On My Way',\n",
       " 'One Only',\n",
       " 'Otro Trago',\n",
       " 'Otro Trago - Remix',\n",
       " 'Otro Trago - Remix',\n",
       " 'Otro Trago - Remix',\n",
       " 'Otro Trago - Remix',\n",
       " 'Oui ou non',\n",
       " 'Oye',\n",
       " 'Pa Mí - Remix',\n",
       " \"Pa' Olvidarme De Ella\",\n",
       " \"Pa' Olvidarme De Ella\",\n",
       " 'Pachtaoge (From \"Jaani Ve\")',\n",
       " 'Pal Pal Dil Ke Paas- Title Track',\n",
       " 'Paprika',\n",
       " 'Para, Pensa e Volta - Ao Vivo',\n",
       " 'Pelukku Untuk Pelikmu - OST Imperfect: Karier, Cinta, & Timbangan',\n",
       " 'Percaya Aku',\n",
       " 'Perreo en La Luna',\n",
       " 'Perreo en La Luna',\n",
       " 'Perreo en La Luna',\n",
       " 'Petit Papa Noël',\n",
       " 'Piensan',\n",
       " 'Pilu Membiru',\n",
       " 'Piropo',\n",
       " 'Pookie (feat. Capo Plaza) - Remix',\n",
       " 'Popopop',\n",
       " 'Prendio - Remix',\n",
       " 'Prendío',\n",
       " 'Pretender',\n",
       " 'Proper Patola',\n",
       " 'Psycho',\n",
       " 'Psycho',\n",
       " 'QUE PRETENDES',\n",
       " 'QUE PRETENDES',\n",
       " 'QUE PRETENDES',\n",
       " 'Quando a vontade bater (Participação especial de PK Delas)',\n",
       " 'Quarta Cadeira - Ao Vivo',\n",
       " 'Que Calor (feat. J Balvin & El Alfa)',\n",
       " 'Que Calor (feat. J Balvin & El Alfa)',\n",
       " 'Que Mas Pues - Remix',\n",
       " 'Que Tire Pa Lante',\n",
       " 'Que Tire Pa Lante',\n",
       " 'Que Tire Pa Lante',\n",
       " 'Que Tire Pa Lante',\n",
       " 'Quem Traiu Levou - Ao Vivo',\n",
       " 'Quizas',\n",
       " 'Quizas',\n",
       " 'Quizas',\n",
       " 'Quizas',\n",
       " 'Quizas',\n",
       " 'Qué Pena',\n",
       " 'Qué Pena',\n",
       " 'RITMO (Bad Boys For Life)',\n",
       " 'RITMO (Bad Boys For Life)',\n",
       " 'RITMO (Bad Boys For Life)',\n",
       " 'RITMO (Bad Boys For Life)',\n",
       " 'RITMO (Bad Boys For Life)',\n",
       " 'RITMO (Bad Boys For Life)',\n",
       " 'RITMO (Bad Boys For Life)',\n",
       " 'RITMO (Bad Boys For Life)',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'ROXANNE',\n",
       " 'Relógio Parado (Ao Vivo)',\n",
       " 'Reste',\n",
       " 'Ride It',\n",
       " 'Ride It',\n",
       " 'Ride It',\n",
       " 'Ride It',\n",
       " \"Rockin' Around The Christmas Tree\",\n",
       " \"Rockin' Around The Christmas Tree\",\n",
       " \"Rockin' Around The Christmas Tree\",\n",
       " \"Rockin' Around The Christmas Tree\",\n",
       " \"Rockin' Around The Christmas Tree\",\n",
       " \"Rockin' Around The Christmas Tree\",\n",
       " \"Rockin' Around The Christmas Tree\",\n",
       " \"Rockin' Around The Christmas Tree\",\n",
       " \"Rockin' Around the Christmas Tree\",\n",
       " 'Roller',\n",
       " 'Roses - Imanbek Remix',\n",
       " 'Rudolph The Red-Nosed Reindeer',\n",
       " 'Rueda',\n",
       " 'Run Rudolph Run - Single Version',\n",
       " 'Run Rudolph Run - Single Version',\n",
       " 'Run Rudolph Run - Single Version',\n",
       " 'Run Rudolph Run - Single Version',\n",
       " 'S de Saudade',\n",
       " 'SENTADÃO',\n",
       " 'STAR',\n",
       " \"SUPREME - L'ego (feat. tha Supreme & Sfera Ebbasta)\",\n",
       " 'Sakhiyaan',\n",
       " 'Sandton',\n",
       " 'Santa Baby',\n",
       " 'Santa Baby',\n",
       " 'Santa Baby',\n",
       " 'Santa Baby',\n",
       " 'Santa Baby',\n",
       " 'Santa Baby (with Henri René & His Orchestra)',\n",
       " \"Santa Claus Is Comin' to Town\",\n",
       " \"Santa Claus Is Comin' to Town - Live at C.W. Post College, Greenvale, NY - December 1975\",\n",
       " \"Santa Claus Is Comin' to Town - Live at C.W. Post College, Greenvale, NY - December 1975\",\n",
       " \"Santa Claus Is Comin' to Town - Live at C.W. Post College, Greenvale, NY - December 1975\",\n",
       " \"Santa Claus Is Comin' to Town - Live at C.W. Post College, Greenvale, NY - December 1975\",\n",
       " \"Santa Claus Is Comin' to Town - Live at C.W. Post College, Greenvale, NY - December 1975\",\n",
       " 'Santa Claus Is Coming To Town',\n",
       " 'Santa Claus Is Coming To Town',\n",
       " 'Santa Claus Is Coming To Town',\n",
       " 'Santa Claus Is Coming To Town',\n",
       " 'Santa Claus Is Coming To Town',\n",
       " 'Santa Claus Is Coming To Town',\n",
       " 'Santa Claus Is Coming to Town',\n",
       " 'Santa Claus Is Coming to Town',\n",
       " 'Santa Claus Is Coming to Town',\n",
       " 'Santa Claus Is Coming to Town',\n",
       " 'Santa Claus Is Coming to Town',\n",
       " 'Santa Claus Is Coming to Town',\n",
       " 'Santa Claus Llegó a La Ciudad',\n",
       " 'Santa Tell Me',\n",
       " 'Santa Tell Me',\n",
       " 'Santa Tell Me',\n",
       " 'Santa Tell Me',\n",
       " 'Santa Tell Me',\n",
       " 'Santa Tell Me',\n",
       " 'Santa Tell Me',\n",
       " 'Santa Tell Me',\n",
       " 'Santa Tell Me',\n",
       " 'Santa Tell Me',\n",
       " 'Santa Tell Me',\n",
       " 'Sauda Khara Khara',\n",
       " 'Sayonara Elegy',\n",
       " 'Se Prepara 2',\n",
       " 'Se iluminaba',\n",
       " 'Secukupnya',\n",
       " 'Selamat (Selamat Tinggal)',\n",
       " 'Sentou e Gostou',\n",
       " 'Serenata - Ao Vivo',\n",
       " 'Señorita',\n",
       " 'Señorita',\n",
       " 'Señorita',\n",
       " 'Señorita',\n",
       " 'Señorita',\n",
       " 'Señorita',\n",
       " 'Señorita',\n",
       " 'Señorita',\n",
       " 'Señorita',\n",
       " 'Señorita',\n",
       " 'Señorita',\n",
       " 'Shaitan Ka Saala (From \"Housefull 4\")',\n",
       " 'Shape of You',\n",
       " 'Shukumei',\n",
       " 'Si Se Da - Remix',\n",
       " 'Si Supieras',\n",
       " 'Si Te Vas',\n",
       " 'Si Te Vas',\n",
       " 'Si Te Vas',\n",
       " 'Si Te Vas',\n",
       " 'Si Te Vas',\n",
       " 'Si por mi fuera',\n",
       " 'Sigues Con El',\n",
       " 'Sigues Con El',\n",
       " 'Sigues Con El',\n",
       " 'Sigues Con El',\n",
       " 'Sigues Con El',\n",
       " 'Skifahren',\n",
       " 'Sleigh Ride',\n",
       " 'Sleigh Ride',\n",
       " 'Sleigh Ride',\n",
       " 'Sleigh Ride',\n",
       " 'Sleigh Ride',\n",
       " 'Sleigh Ride',\n",
       " 'So Am I',\n",
       " 'Soldi in Nero - feat. Sfera Ebbasta',\n",
       " 'Solteiro Não Trai - Ao Vivo',\n",
       " 'Soltera - Remix',\n",
       " 'Soltera - Remix',\n",
       " 'Soltera - Remix',\n",
       " 'Soltera - Remix',\n",
       " 'Some que ele vem atrás',\n",
       " 'Someone You Loved',\n",
       " 'Someone You Loved',\n",
       " 'Someone You Loved',\n",
       " 'Someone You Loved',\n",
       " 'Someone You Loved',\n",
       " 'Sorbito De Champagne - Digitally Remastered Original',\n",
       " 'Soy Sabalero',\n",
       " 'Speechless (Full)',\n",
       " 'Stand By You',\n",
       " 'Step Into Christmas',\n",
       " 'Step Into Christmas',\n",
       " 'Step Into Christmas',\n",
       " 'Step Into Christmas',\n",
       " 'Street',\n",
       " 'Sukendleleni',\n",
       " 'Sunflower - Spider-Man: Into the Spider-Verse',\n",
       " 'Sunflower - Spider-Man: Into the Spider-Verse',\n",
       " 'Supera - Ao Vivo',\n",
       " 'Surtada - Remix Brega Funk',\n",
       " 'Tabaco y Ron',\n",
       " 'Tak Ingin Pisah Lagi',\n",
       " 'Takeaway',\n",
       " 'Takeaway',\n",
       " 'Tal Vez',\n",
       " 'Tal Vez',\n",
       " 'Tanpa Tergesa',\n",
       " 'Te Quemaste',\n",
       " 'Te Vi',\n",
       " 'Teenager Forever',\n",
       " 'Tender Love (feat. DJ Maphorisa & Kabza De Small)',\n",
       " 'Tera Ban Jaunga (From \"Kabir Singh\")',\n",
       " \"Thank God It's Christmas - Non-Album Single\",\n",
       " \"Thank God It's Christmas - Non-Album Single\",\n",
       " 'The Best Side Of Life',\n",
       " 'The Box',\n",
       " 'The Box',\n",
       " 'The Christmas Song (Merry Christmas To You)',\n",
       " 'The Christmas Song (Merry Christmas To You)',\n",
       " 'The Christmas Song (Merry Christmas To You)',\n",
       " 'The Christmas Song (Merry Christmas To You)',\n",
       " 'The Christmas Song (Merry Christmas To You)',\n",
       " 'The Christmas Song (Merry Christmas To You)',\n",
       " 'This Christmas',\n",
       " 'This Christmas',\n",
       " 'Ti volevo dedicare (feat. J-AX & Boomdabash)',\n",
       " 'Tijolão - Ao Vivo',\n",
       " 'Tiro Certo - Ao Vivo',\n",
       " 'To Voando Alto',\n",
       " 'Todo Mundo Vai Sofrer - Ao Vivo',\n",
       " 'Tolong',\n",
       " 'Traicionera',\n",
       " 'Trampoline (with ZAYN)',\n",
       " 'Trampoline (with ZAYN)',\n",
       " 'Trampoline (with ZAYN)',\n",
       " 'Tu Hi Yaar Mera (From \"Pati Patni Aur Woh\")',\n",
       " 'Tujhe Kitna Chahne Lage (From \"Kabir Singh\")',\n",
       " 'Tum Hi Aana (From \"Marjaavaan\")',\n",
       " 'Turning Up',\n",
       " 'Tusa',\n",
       " 'Tusa',\n",
       " 'Tusa',\n",
       " 'Tusa',\n",
       " 'Tusa',\n",
       " 'Tusa',\n",
       " 'Tutto Questo Sei Tu',\n",
       " 'Tutu',\n",
       " 'Tutu',\n",
       " 'Tutu',\n",
       " 'Tutu',\n",
       " 'Umbrella',\n",
       " 'Umlilo',\n",
       " 'Un million par mois',\n",
       " 'Un peu de haine',\n",
       " 'Una Cerveza',\n",
       " 'Una Vida Para Recordar',\n",
       " 'Una volta ancora (feat. Ana Mena)',\n",
       " 'Underneath the Tree',\n",
       " 'Underneath the Tree',\n",
       " 'Underneath the Tree',\n",
       " 'Underneath the Tree',\n",
       " 'Underneath the Tree',\n",
       " 'Underneath the Tree',\n",
       " 'Underneath the Tree',\n",
       " 'Underneath the Tree',\n",
       " 'Underneath the Tree',\n",
       " 'Unfaithful',\n",
       " 'Vaaste',\n",
       " 'Ve Maahi',\n",
       " \"Ve'Eem Tavo'ee Elay (And If You Will Come To Me)\",\n",
       " 'Verdinha',\n",
       " 'Verte Ir',\n",
       " 'Vete',\n",
       " 'Vete',\n",
       " 'Vete',\n",
       " 'Vete',\n",
       " 'Vete',\n",
       " 'Vor der Tür',\n",
       " 'Vou Ter Que Superar - Ao Vivo',\n",
       " 'Vula Vala',\n",
       " 'Víspera de Año Nuevo',\n",
       " 'Waktu Yang Salah',\n",
       " 'Walking with you',\n",
       " 'Watermelon Sugar',\n",
       " 'Way Back Home (feat. Conor Maynard) - Sam Feldt Edit',\n",
       " 'What Christmas Means To Me',\n",
       " 'What Christmas Means To Me',\n",
       " 'Wherever you are',\n",
       " 'Whine Up',\n",
       " 'Whine Up',\n",
       " 'Whine Up',\n",
       " 'Whine Up',\n",
       " 'Whine Up',\n",
       " 'White Christmas',\n",
       " 'White Christmas',\n",
       " 'White Christmas',\n",
       " 'White Christmas',\n",
       " 'White Christmas',\n",
       " 'White Christmas',\n",
       " 'White Christmas (with Shania Twain)',\n",
       " 'Wieso tust Du dir das an?',\n",
       " 'Winter Wonderland',\n",
       " 'Winter Wonderland',\n",
       " 'Winter Wonderland - Remastered 2006',\n",
       " 'Woin Woin feat. RK',\n",
       " 'Wonderful Christmastime - Edited Version / Remastered 2011',\n",
       " 'Wonderful Christmastime - Edited Version / Remastered 2011',\n",
       " 'Wonderful Christmastime - Edited Version / Remastered 2011',\n",
       " 'Wonderful Christmastime - Edited Version / Remastered 2011',\n",
       " 'Wonderful Christmastime - Edited Version / Remastered 2011',\n",
       " 'Wonderful Christmastime - Edited Version / Remastered 2011',\n",
       " 'Wonderful Christmastime - Edited Version / Remastered 2011',\n",
       " 'Wonderful Dream (Holidays Are Coming) - Radio Version',\n",
       " 'Ya No Mas',\n",
       " 'Yaad Piya Ki Aane Lagi',\n",
       " 'Yesterday',\n",
       " 'Yo x Ti, Tu x Mi',\n",
       " 'Yo x Ti, Tu x Mi',\n",
       " 'Yo x Ti, Tu x Mi',\n",
       " 'Yo x Ti, Tu x Mi',\n",
       " 'You Make It Feel Like Christmas (feat. Blake Shelton)',\n",
       " 'Zorra',\n",
       " 'bad guy',\n",
       " 'bad guy',\n",
       " 'bad guy',\n",
       " 'bad guy',\n",
       " 'bad guy',\n",
       " 'blun7 a swishland',\n",
       " 'ch1 5ei te',\n",
       " 'choque térmico - ao vivo',\n",
       " 'comethru',\n",
       " 'comethru',\n",
       " 'everything i wanted',\n",
       " 'everything i wanted',\n",
       " 'everything i wanted',\n",
       " 'everything i wanted',\n",
       " 'fuck 3x',\n",
       " 'hot girl bummer',\n",
       " 'hot girl bummer',\n",
       " 'lowkey',\n",
       " 'm12ano - feat. Mara Sattei',\n",
       " 'm8nstar',\n",
       " 'menina solta',\n",
       " 'occh1 purpl3 - feat. Marracash',\n",
       " 'quando a bad bater - ao vivo',\n",
       " 'sw1n6o - feat. Salmo',\n",
       " 'Áudio - Ao Vivo em Brasília']"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "descargar = [\"title\",\"artist\"]\n",
    "df_descargar= df[descargar]\n",
    "list(df_descargar.title)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Descargamos de la Api de Deezer y hacemos una columna nueva"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'ROXANNE'"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def buscarAlbum(albunes):    \n",
    "    if albunes[\"total\"] != 0:\n",
    "        for elemento in albunes.items():    \n",
    "            for elem in elemento:\n",
    "                if type(elem) == list:\n",
    "                    for x,y in elem[0].items():\n",
    "                        if x == \"title\":\n",
    "                            return y\n",
    "    else:    \n",
    "        return None\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "def descargar(df):\n",
    "    albunes = []\n",
    "    for index,row in df.iterrows():\n",
    "        titulo = row.title\n",
    "        artista = row.artist\n",
    "        artists_url = f\"https://api.deezer.com/search?q=artist:'{artista}' track:'{titulo}'\"\n",
    "        artists_response = requests.get(artists_url)\n",
    "        album =artists_response.json()\n",
    "        try:\n",
    "            albunes.append(buscarAlbum(album))\n",
    "        except:\n",
    "            albunes.append(None)\n",
    "\n",
    "    return albunes\n",
    "d_albunes = descargar(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>artist</th>\n",
       "      <th>top genre</th>\n",
       "      <th>year</th>\n",
       "      <th>country</th>\n",
       "      <th>val</th>\n",
       "      <th>albums</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>10,000 Hours (with Justin Bieber)</td>\n",
       "      <td>Dan + Shay</td>\n",
       "      <td>contemporary country</td>\n",
       "      <td>2019</td>\n",
       "      <td>indonesia</td>\n",
       "      <td>43</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>10,000 Hours (with Justin Bieber)</td>\n",
       "      <td>Dan + Shay</td>\n",
       "      <td>contemporary country</td>\n",
       "      <td>2019</td>\n",
       "      <td>malasya</td>\n",
       "      <td>43</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>100 Degrees</td>\n",
       "      <td>Rich Brian</td>\n",
       "      <td>indonesian hip hop</td>\n",
       "      <td>2019</td>\n",
       "      <td>indonesia</td>\n",
       "      <td>66</td>\n",
       "      <td>100 Degrees</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>105 F Remix</td>\n",
       "      <td>KEVVO</td>\n",
       "      <td>perreo</td>\n",
       "      <td>2019</td>\n",
       "      <td>chile</td>\n",
       "      <td>74</td>\n",
       "      <td>105 F Remix</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>105 F Remix</td>\n",
       "      <td>KEVVO</td>\n",
       "      <td>perreo</td>\n",
       "      <td>2019</td>\n",
       "      <td>spain</td>\n",
       "      <td>74</td>\n",
       "      <td>105 F Remix</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>930</th>\n",
       "      <td>menina solta</td>\n",
       "      <td>Giulia Be</td>\n",
       "      <td>pop nacional</td>\n",
       "      <td>2019</td>\n",
       "      <td>brazil</td>\n",
       "      <td>67</td>\n",
       "      <td>menina solta</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>931</th>\n",
       "      <td>occh1 purpl3 - feat. Marracash</td>\n",
       "      <td>tha Supreme</td>\n",
       "      <td>trap italiana</td>\n",
       "      <td>2019</td>\n",
       "      <td>italy</td>\n",
       "      <td>55</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>932</th>\n",
       "      <td>quando a bad bater - ao vivo</td>\n",
       "      <td>Luan Santana</td>\n",
       "      <td>funk carioca</td>\n",
       "      <td>2019</td>\n",
       "      <td>brazil</td>\n",
       "      <td>53</td>\n",
       "      <td>quando a bad bater (ao vivo)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>933</th>\n",
       "      <td>sw1n6o - feat. Salmo</td>\n",
       "      <td>tha Supreme</td>\n",
       "      <td>trap italiana</td>\n",
       "      <td>2019</td>\n",
       "      <td>italy</td>\n",
       "      <td>79</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>934</th>\n",
       "      <td>Áudio - Ao Vivo em Brasília</td>\n",
       "      <td>Diego &amp; Victor Hugo</td>\n",
       "      <td>sertanejo pop</td>\n",
       "      <td>2019</td>\n",
       "      <td>brazil</td>\n",
       "      <td>45</td>\n",
       "      <td>Jaleo</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>935 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                 title               artist  \\\n",
       "0    10,000 Hours (with Justin Bieber)           Dan + Shay   \n",
       "1    10,000 Hours (with Justin Bieber)           Dan + Shay   \n",
       "2                          100 Degrees           Rich Brian   \n",
       "3                          105 F Remix                KEVVO   \n",
       "4                          105 F Remix                KEVVO   \n",
       "..                                 ...                  ...   \n",
       "930                       menina solta            Giulia Be   \n",
       "931     occh1 purpl3 - feat. Marracash          tha Supreme   \n",
       "932       quando a bad bater - ao vivo         Luan Santana   \n",
       "933               sw1n6o - feat. Salmo          tha Supreme   \n",
       "934        Áudio - Ao Vivo em Brasília  Diego & Victor Hugo   \n",
       "\n",
       "                top genre  year    country  val                        albums  \n",
       "0    contemporary country  2019  indonesia   43                          None  \n",
       "1    contemporary country  2019    malasya   43                          None  \n",
       "2      indonesian hip hop  2019  indonesia   66                   100 Degrees  \n",
       "3                  perreo  2019      chile   74                   105 F Remix  \n",
       "4                  perreo  2019      spain   74                   105 F Remix  \n",
       "..                    ...   ...        ...  ...                           ...  \n",
       "930          pop nacional  2019     brazil   67                  menina solta  \n",
       "931         trap italiana  2019      italy   55                          None  \n",
       "932          funk carioca  2019     brazil   53  quando a bad bater (ao vivo)  \n",
       "933         trap italiana  2019      italy   79                          None  \n",
       "934         sertanejo pop  2019     brazil   45                         Jaleo  \n",
       "\n",
       "[935 rows x 7 columns]"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df[\"albums\"] = d_albunes\n",
    "df"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Miramos los nulos y eliminamos esos registros."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "title         0\n",
       "artist        0\n",
       "top genre     0\n",
       "year          0\n",
       "country       0\n",
       "val           0\n",
       "albums       90\n",
       "dtype: int64"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.isnull().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "df.drop(df[df.albums.isnull()].index, inplace=True)  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "df.to_csv('terminado.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
